name: market_data_platform
version: "1.0.0"
config-version: 2

profile: market_data_platform

model-paths: ["models"]
macro-paths: ["macros"]

models:
  market_data_platform:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

flags:
  bigquery_use_batch_source_freshness: true
