market_data_platform:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('PROJECT_ID') }}"
      dataset: staging
      location: europe-west1
      threads: 2
      maximum_bytes_billed: 31457280
      job_execution_timeout_seconds: 300
      job_retries: 1
